### ISSUE TITLE
Android Auto: 59.00.441 NA N

### ISSUE THREAD

**Issue by creativekindle** [Trevelopment/MZD-AIO-TI#34]
Used AIO 2.4 on top of 59.00.441 NA N (2016.5 CX5). Removal of disclaimer works, as well as, touchscreen while driving.

Android Auto says it installs but doesn't actually ever show up under applications. And while "installed" there's a bug that causes phone call bluetooth to bounce back to the phone rather than car speaker. Only calls. Media works.

AA uninstallation works & phone/car bluetooth handshake resumes.

What can I do/supply to help (if anything)?

**Comment by creativekindle** [comment]
Don't see how to edit on mobile...

Meant to end with, what can I do to help?

**Comment by Trevelopment** [comment]
OK these are both known issues.  When you did the remove disclaimer tweak did you  have it on 'remove completely' because there is a patch that is included in that weak and also order of audio source list that lets the apps like AA, speedometer, video player, show up in the app menu.  

Also someone else is developing AA sothe issue has been raised over in the proper repo.

**Comment by creativekindle** [comment]
When I did the original install I only attempted AA via AIO, which to me it didn't look like anything worked. Then I tried AA with touchscreen enabled (and again it looked like AA didn't work but touchscreen did). And then I went back for a third time with AA, touchscreen & disclaimer (remove completely), again only AA didn't work. It wasn't until this point did I notice the BT handoff.

OK, thanks!
